apiVersion: v1                           # Specifies the Kubernetes API version for Service resource
kind: Service                            # Defines the type of resource as a Service
metadata:
  name: httpbin-nodeport                 # Sets the name of the Service
spec:
  type: NodePort                         # Specifies the service type as NodePort (accessible externally via Node IPs)
  selector:
    app: httpbin                         # Selects pods with the label app: httpbin
  ports:
    - port: 80                           # Service port accessible within the cluster
      targetPort: 80                     # Maps to container's port 80
      nodePort: 30002                    # Sets a static port on each Node to expose the service
