apiVersion: apps/v1         # Specifies the API version for the Kubernetes resource, in this case, it's a Deployment, which is part of the 'apps/v1' API group.
kind: Deployment            # Defines the kind of Kubernetes resource you're creating, here it's a Deployment for my SQL.
metadata:
  name: mysql-deployment    # Metadata section where 'name' defines the name of the Deployment, here it’s 'mysql-deployment'.
spec:
  replicas: 1               # Specifies the number of instances to run for mysql database
  selector:
    matchLabels:
      app: mysql-deploy    # The selector is used to find which pods this Deployment manages, matching pods with the label 'app: mysql-deploy'.
  template:                # Template defines the pod template used by the Deployment to create new pods.
    metadata:
      labels:              
        app: mysql-deploy   # Labels to be applied to the pods created by this Deployment. Here, the label 'app: mysql-deploy' is added.
    spec:
      containers:           # Specifies the list of containers that will run inside the pod.
        - name: mysql       # The name of the container running in the pod. In this case, it's named 'mysql'.
          image: mysql:8.0  # The Docker image used for this container, here it's the official 'mysql:5.7' image from Docker Hub.
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootword"   # This environment variable sets the root password for MySQL.
          resources:
            requests:
              cpu: "100m"  # Minimum CPU the container can use is 100 milliCPU (0.1 of a CPU core)
              memory: "128Mi"  # Minimum memory requested (128Mi, or 128 megabytes)
            limits:
              cpu: "200m"  # The maximum CPU this container can use (200m, or 0.2 CPU)
              memory: "256Mi"  # The maximum amount of memory this container can use (256MiB)
          ports:
            - containerPort: 3306  # MySQL’s default port, exposed for connections.