apiVersion: v1                             # Specifies the Kubernetes API version for Service resource
kind: Service                              # Defines the type of resource as a Service
metadata:
  name: flask-loadbalancer                 # Sets the name of the Service
spec:
  type: LoadBalancer                        # Specifies the service type as LoadBalancer (publicly accessible)
  selector:
    app: flask                              # Selects pods with the label app: flask
  ports:
    - port: 80                              # Service port for public access
      targetPort: 80                        # Maps to container's port 80
