apiVersion: apps/v1               # Specifies the API version used for the Deployment resource
kind: Deployment                  # Defines the type of resource we are creating, which is a Deployment
metadata:
  name: redis-deployment                 # The name of the Deployment is 'redis-app'
spec:
  replicas: 1                    # Number of replicas is 10, as this is the total number of Pods
  selector:
    matchLabels:
      app: redis-deploy             # Selector matches Pods that have the label 'app: redis-app'
  template:
    metadata:
      labels:
        app: redis-deploy            # Pods created by this template will have the label 'app: redis-app'
    spec:
      containers:
      - name: redis-container     # Name of the container is 'redis-container'
        image: redis:6.0.9        # The Docker image for the container is Redis version 6.0.9 (initial version)
        resources:
            requests:
              cpu: "100m"  # Minimum CPU the container can use is 100 milliCPU (0.1 of a CPU core)
              memory: "128Mi"  # Minimum memory requested (128Mi, or 128 megabytes)
            limits:
              cpu: "200m"  # The maximum CPU this container can use (200m, or 0.2 CPU)
              memory: "256Mi"  # The maximum amount of memory this container can use (256MiB)
        ports:
        - containerPort: 6379     # Exposes port 6379 on the container for Redis traffic
